ssm-jump: add ability to use internal IP and instance ID as target

diff --git a/ssm-jump b/ssm-jump
--- a/ssm-jump
+++ b/ssm-jump
@@ -18,7 +18,7 @@ while [[ $# -gt 0 ]]; do
 
   case ${key} in
     -h | --help)
-      echo "Usage: ssh-jump.sh [options] hostname"
+      echo "Usage: ssh-jump.sh [options] internal-ip|instance-id|instance-name"
       echo "Options:"
       echo "  -h, --help                                   Print this help message"
       echo "  -p, --profile <profile>                      Specify the aws cli profile to use"
@@ -50,11 +50,14 @@ done
 
 set -- "${positional[@]}" # restore positional parameters
 
+# first positional argument is the target
+target="${1}"
+
 if [ -z "${profile}" ]; then
   fatal "No profile specified !"
 fi
 
-if [ -z "${1}" ]; then
+if [ -z "${target}" ]; then
   fatal "No target specified !"
 fi
 
@@ -65,7 +68,25 @@ if [ ! -z "${forward}" ]; then
   fi
 fi
 
-instances=$(aws --profile "${profile}" ec2 describe-instances --filters "Name=instance-state-name,Values=running" "Name=tag:Name,Values=${1}" --query "Reservations[*].Instances[*].{a: InstanceId, b: PrivateIpAddress, c: Tags[?Key=='Name'] | [0].Value}" --output text | sort -n)
+# perform target lookup (AWS SSM target *must* be an EC2 instance ID)
+if echo "${target}" | grep -qE '^i-.*'; then
+  instances="${target} NONE NONE"
+  echo "using instance ID ${target}" >&2
+elif echo "${target}" | grep -qE '^([0-9]{1,3}\.){3}[0-9]{1,3}$'; then
+  filter="Name=private-ip-address,Values=${target}"
+elif echo "${target}" | grep -qE '^[a-z0-9\-]+$'; then
+  filter="Name=tag:Name,Values=${target}"
+else
+  fatal "Invalid target '${target}' !"
+fi
+
+if [ -n "${filter}" ]; then
+  instances="$(aws --profile "${profile}" ec2 describe-instances --filters "Name=instance-state-name,Values=running" "${filter}" --query "Reservations[*].Instances[*].{a: InstanceId, b: PrivateIpAddress, c: Tags[?Key=='Name'] | [0].Value}" --output text | sort -n)"
+
+  if [ -z "${instances}" ]; then
+	fatal "Unable to detect any instance for target ${target}"
+  fi
+fi
 
 if [ "$(echo "${instances}" | wc -l | tr -d ' ')" = "1" ]; then
   instance_id=$(echo "${instances}" | awk '{ print $1 }')
